import {availableContent,displayNumber,reportedNumber,resultContent,resultObject,resultRows,resultText,vectorCsv,visibleInput,type Json} from './result-contract';

function downloadCsv(index:unknown,value:unknown) {
 const url=URL.createObjectURL(new Blob([vectorCsv(value)],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`embedding-${String(index).replace(/[^0-9]/g,'')||'0'}.csv`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function Usage({value}:{value:unknown}) {
 const usage=resultObject(value);
 return <><dl className="noedaeri-metrics"><div><dt>입력 토큰</dt><dd>{displayNumber(usage.prompt_tokens)}</dd></div><div><dt>출력 토큰</dt><dd>{displayNumber(usage.completion_tokens)}</dd></div><div><dt>총 토큰</dt><dd>{displayNumber(usage.total_tokens)}</dd></div></dl><p className="small muted">공급자 보고값이며 누락은 미확인입니다. 토큰만으로 비용·무료 잔여 한도를 판단하지 않습니다.</p></>;
}
function Answer({value}:{value:unknown}) {
 if(typeof value==='string')return <pre className="noedaeri-output">{value}</pre>;
 const answer=resultObject(value);
 if(Array.isArray(answer.tags))return <ul className="noedaeri-tags">{answer.tags.map((tag,index)=><li key={index}>{resultText(tag)}</li>)}</ul>;
 if(typeof answer.summary==='string'||typeof answer.comment==='string'||typeof answer.reply==='string')return <pre className="noedaeri-output">{resultText(answer.summary??answer.comment??answer.reply)}</pre>;
 if(answer.skip===true)return <p>작성할 초안 없음 · {resultText(answer.reason)||'원본 결과의 사유를 확인하세요.'}</p>;
 if(typeof answer.title==='string'&&Array.isArray(answer.paragraphs))return <article><h5>{answer.title}</h5>{answer.paragraphs.map((paragraph,index)=><pre className="noedaeri-output" key={index}>{resultText(paragraph)}</pre>)}{answer.sources!==undefined&&<details><summary>참고 출처 · 원본 보고</summary><pre>{resultText(answer.sources)}</pre></details>}</article>;
 return <pre className="noedaeri-output">{resultText(value)}</pre>;
}
export function NoedaeriResult({value,context,request}:{value:unknown;context:string;request:Json|null}) {
 const row=resultObject(value),content=resultContent(row),input=visibleInput(request,row),vectors=resultRows(row.data),matches=resultRows(row.results),summary=resultRows(row.summary),records=resultRows(row.records);
 const expired=!availableContent(row),answer=content.translated_text??content.ai_result,probabilities=resultObject(row.probabilities);
 if(context==='collections')return <><h4>컬렉션 통계</h4><p className="small muted">현재 환경의 영속 색인 문서입니다. 작업 결과 요약 만료와 문서 삭제는 다릅니다. 토큰은 저장 문서의 추정치이며 전체 호출 사용량이 아닙니다.</p>{resultRows(value).length===0?<p>이 범위에 색인 컬렉션이 없습니다.</p>:<div className="noedaeri-table"><table><thead><tr><th>컬렉션</th><th>문서</th><th>모델·차원</th><th>추정 토큰</th><th>최근 변경</th></tr></thead><tbody>{resultRows(value).map((item,index)=><tr key={index}><td>{resultText(item.collection)}</td><td>{displayNumber(item.document_count)}</td><td>{resultText(item.model)} · {displayNumber(item.dimensions)}</td><td>{displayNumber(item.total_tokens)}</td><td>{resultText(item.last_updated_at)}</td></tr>)}</tbody></table></div>}</>;
 return <>
  {!expired&&row.model_tier!==undefined&&row.probabilities!==undefined&&<section><h4>Raya 추천 · {resultText(row.model_tier)}</h4><p>confidence {displayNumber(row.confidence)} · 확률과 confidence는 정답률이나 안전성 판정이 아닙니다.</p><div className="noedaeri-probabilities">{['L1','L2','L3'].map(tier=>{const probability=reportedNumber(probabilities[tier]);return <label key={tier}>{tier}<meter aria-label={`${tier} 예측 확률`} min={0} max={1} value={probability??0}/><span>{probability===null?'미확인':(probability*100).toFixed(2)+'%'}</span></label>;})}</div>{row.input_truncated===true&&<p className="warning">입력이 잘려 앞부분만 판단했습니다. 전체 요청의 난이도를 보장하지 않습니다.</p>}<dl className="noedaeri-metrics"><div><dt>라우터 입력 토큰</dt><dd>{displayNumber(row.input_tokens)}</dd></div><div><dt>추론</dt><dd>{displayNumber(row.inference_ms)} ms</dd></div><div><dt>전체 시간</dt><dd>{displayNumber(row.elapsed_ms)} ms</dd></div><div><dt>최초 로딩</dt><dd>{row.cold_start===true?'포함':row.cold_start===false?'없음':'미확인'}</dd></div></dl><p className="small muted">{resultText(row.model)} · {resultText(row.device)} / {resultText(row.runtime)} · revision {resultText(row.revision)}. 라우터 지표는 외부 모델 사용량과 별개입니다.</p></section>}
  {!expired&&Array.isArray(row.data)&&row.dimensions!==undefined&&<section><h4>임베딩 벡터</h4><p>{resultText(row.model)} · 요청 차원 {displayNumber(row.dimensions)} · {vectors.length}개</p><p className="small muted">첫 8개 값만 표시합니다. JSON 다운로드와 각 벡터 CSV에는 전체 값이 있습니다. 다른 모델·차원의 기존 색인과 섞지 마세요.</p><div className="noedaeri-table"><table><thead><tr><th>입력 순번</th><th>실제 차원</th><th>벡터 앞부분</th><th>다운로드</th></tr></thead><tbody>{vectors.map((item,index)=>{const vector=Array.isArray(item.embedding)?item.embedding:[],valid=vector.length>0&&vector.every(value=>reportedNumber(value)!==null);return <tr key={index}><td>{displayNumber(item.index)}</td><td>{vector.length}{vector.length!==row.dimensions&&' · 응답 차원 불일치'}</td><td><code>{vector.slice(0,8).map(value=>displayNumber(value)).join(', ')}</code></td><td><button className="secondary" disabled={!valid} onClick={()=>downloadCsv(item.index,vector)}>전체 CSV</button></td></tr>;})}</tbody></table></div><Usage value={row.usage}/></section>}
  {(row.status!==undefined&&row.task_type!==undefined||context==='jobs'||context==='translation')&&!Array.isArray(value)&&<section><h4>{content.type==='text_translate'?'번역 원문·결과':'AI 입력·결과'}</h4><div className="noedaeri-comparison"><article><h5>보낸 입력</h5>{input===null?<p className="small muted">이전 실행 원문은 플랫폼 이력에 저장하지 않습니다. 현재 화면에서 보낸 입력만 비교할 수 있습니다.</p>:<pre className="noedaeri-output">{input}</pre>}</article><article><h5>모델 출력</h5>{expired?<p>만료 또는 수령 확인으로 결과가 닫혔습니다.</p>:answer===undefined?<p>{row.status==='succeeded'?'표시할 ai_result/translated_text가 없습니다. 원본 JSON의 결과 계약을 확인하세요.':'실행 완료 후 표시합니다.'}</p>:<Answer value={answer}/>}</article></div>{Object.keys(content).length>0&&<><dl className="noedaeri-metrics"><div><dt>공급자</dt><dd>{resultText(content.provider)||'미확인'}</dd></div><div><dt>보고된 모델</dt><dd>{resultText(content.model)||'미확인'}</dd></div><div><dt>보고된 등급</dt><dd>{resultText(content.model_tier)||'미확인'}</dd></div>{content.target_language!==undefined&&<div><dt>번역 언어</dt><dd>{resultText(content.source_language)} → {resultText(content.target_language)}</dd></div>}</dl><Usage value={content.usage}/>{content.retrieved_context!==undefined&&<details><summary>검색된 참고 문맥</summary><pre className="noedaeri-output">{resultText(content.retrieved_context)}</pre></details>}</>}<p className="small muted">모델 식별·사용량은 보고 기준입니다. 블로그 저장·댓글 게시·UI 변경을 자동 적용하지 않으며 호스트의 출력 검증과 사용자 검토가 필요합니다.</p></section>}
  {row.mode!==undefined&&row.collection!==undefined&&<section><h4>색인 변경 · {resultText(row.collection)}</h4><p>모드 {resultText(row.mode)} · 이력 기준 변경 수입니다. 결과 요약 만료가 색인 문서를 삭제하지 않습니다.</p><dl className="noedaeri-metrics"><div><dt>요청 문서</dt><dd>{displayNumber(row.document_count)}</dd></div><div><dt>색인한 문서</dt><dd>{displayNumber(row.indexed_count)}</dd></div><div><dt>삭제한 문서</dt><dd>{displayNumber(row.deleted_count)}</dd></div><div><dt>추정 토큰</dt><dd>{displayNumber(row.total_tokens)}</dd></div></dl>{Object.keys(content).length>0&&<p className="small muted">{resultText(content.model)} · {displayNumber(content.dimensions)}차원 · {content.usage_estimated===true?'추정 사용량 (공급자 청구량 아님)':'토큰 측정 방식 미확인'}</p>}</section>}
  {!expired&&Array.isArray(row.results)&&<section><h4>벡터 검색 · {resultText(row.collection)}</h4><p>질의: {resultText(row.query)} · 후보 {displayNumber(row.total_candidates)} / 검색 결과 {displayNumber(row.matched_count)}</p>{matches.length===0&&<p>관련 문서를 찾지 못했습니다. 범위와 색인 완료 상태를 확인하세요. 빈 결과를 근거 없는 답변으로 대체하지 않습니다.</p>}{matches.map((item,index)=><article className="noedaeri-search-result" key={index}><h5>{resultText(item.title)||resultText(item.document_id)}</h5><p className="small muted">문서 {resultText(item.document_id)} · 코사인 유사도 {displayNumber(item.similarity)} (정답률 아님)</p><pre className="noedaeri-output">{resultText(item.content)}</pre><details><summary>문서 메타데이터</summary><pre className="noedaeri-output">{resultText(item.metadata)}</pre></details></article>)}</section>}
  {context==='usage'&&<section><h4>공급자 보고 사용량</h4>{summary.length===0?<p>이 범위의 사용량 보고가 없습니다. 모델을 호출하지 않았거나 비용이 0이라는 뜻은 아닙니다.</p>:<div className="noedaeri-table"><table><thead><tr><th>공급자·모델</th><th>작업</th><th>호출</th><th>입력 토큰</th><th>출력 토큰</th><th>총 토큰</th></tr></thead><tbody>{summary.map((item,index)=><tr key={index}><td>{resultText(item.provider)} / {resultText(item.model)}</td><td>{resultText(item.task_type)}</td><td>{displayNumber(item.call_count)}</td><td>{displayNumber(item.total_prompt_tokens)}</td><td>{displayNumber(item.total_completion_tokens)}</td><td>{displayNumber(item.total_tokens)}</td></tr>)}</tbody></table></div>}<details><summary>호출 상세 {records.length}건</summary><div className="noedaeri-table"><table><thead><tr><th>시각·요청 ID</th><th>작업·모델</th><th>입력 / 출력 / 총 토큰</th></tr></thead><tbody>{records.map((item,index)=><tr key={index}><td>{resultText(item.created_at)}<br/>{resultText(item.request_id)}</td><td>{resultText(item.task_type)}<br/>{resultText(item.provider)} / {resultText(item.model)}</td><td>{displayNumber(item.prompt_tokens)} / {displayNumber(item.completion_tokens)} / {displayNumber(item.total_tokens)}</td></tr>)}</tbody></table></div></details><p className="small muted">보고된 호출별 집계입니다. 누락·추정·공급자 실측·비용·무료 한도는 구분하며 라우터 지표를 합산하지 않습니다.</p></section>}
 </>;
}
